[package]
name = "zoo-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
fluent-bundle = "0.16.0"
fluent-syntax = "0.12.0"
glam = "0.33.10"
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.6"
unic-langid = "0.9.6"
