[package]
name = "zoo-web"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
glam = "0.33.10"
wasm-bindgen = "0.2.129"
zoo-core = { version = "0.1.0", path = "../zoo-core" }
zoo-render = { version = "0.1.0", path = "../zoo-render" }
