// Art review catalog — rendered by art/index.html.
// Plain JS (not JSON) so the page works when opened directly from disk (file://).
// Paths are relative to art/. Status values: planned | brief | in-review | changes-requested | approved.
// "approved" must match concept_approved = true in assets/manifest.toml (ART-PIPELINE).
window.ART_CATALOG = {
  updated: "2026-09-26",
  sections: [
    {
      id: "reference",
      title: "Reference",
      intro: "External reference images that define the target look. Not our own assets.",
      items: [
        {
          id: "ref_player_farm",
          title: "Player character style",
          status: "reference",
          description: "Blocky/voxel girl in a striped shirt walking with a bear, sheep and chick. Reference for player character proportions, warm daylight and the overall blocky style.",
          spec: "ART-DIRECTION",
          images: [{ file: "reference/ref-player-style.jpg", label: "reference" }],
        },
        {
          id: "ref_enclosure_row",
          title: "Enclosure row with signs",
          status: "reference",
          description: "Row of enclosures with signs showing the animal name and a silhouette, wooden fences, open grass field with hippos, zebras and a snow fox.",
          spec: "ART-DIRECTION",
          images: [{ file: "reference/ref-enclosure-row.jpg", label: "reference" }],
        },
        {
          id: "ref_enclosure_buildings",
          title: "Distinct enclosure buildings",
          status: "reference",
          description: "Each animal has a recognisable building: wooden hut (hippo), stone arch (zebra), glass house (snow fox). Large readable wooden signs.",
          spec: "ART-DIRECTION",
          images: [{ file: "reference/ref-enclosure-buildings.jpg", label: "reference" }],
        },
        {
          id: "ref_zoo_layout",
          title: "Zoo layout (stylised, non-voxel)",
          status: "reference",
          description: "Isometric zoo with paths, kiosks and props in a smooth stylised look. Its purpose is still open (Q-010): layout reference only, or also style?",
          spec: "ART-DIRECTION",
          images: [{ file: "reference/ref-zoo-layout.webp", label: "reference" }],
        },
      ],
    },
    {
      id: "characters",
      title: "Characters",
      intro: "Human characters. Turnaround sheet required before modelling: front, side, back, ¾.",
      items: [
        {
          id: "player_girl",
          title: "Player — girl",
          status: "brief",
          description: "Playable girl, ~6–8 years old, blocky style close to the reference image.",
          spec: "ART-CHARACTERS",
          brief: "characters/player_girl/brief.md",
          notes: "Proposal: 1.20 m, head-to-body 1 : 3.5, long dark-brown hair, white/blue striped shirt, jeans. Rig and animations: ART-RIG. Turnaround images not generated yet (Q-009).",
          images: [
            { file: "characters/player_girl/front.png", label: "front", required: true },
            { file: "characters/player_girl/side.png", label: "side", required: true },
            { file: "characters/player_girl/back.png", label: "back", required: true },
            { file: "characters/player_girl/three_quarter.png", label: "¾", required: true },
            { file: "characters/player_girl/expressions.png", label: "expressions" },
          ],
        },
        {
          id: "player_boy",
          title: "Player — boy",
          status: "brief",
          description: "Playable boy, matching counterpart to the girl, same rig and proportions.",
          spec: "ART-CHARACTERS",
          brief: "characters/player_boy/brief.md",
          notes: "New design, please review: short chestnut hair with a tuft, mustard-yellow shirt with a green band, navy shorts, green sneakers. Turnaround images not generated yet (Q-009).",
          images: [
            { file: "characters/player_boy/front.png", label: "front", required: true },
            { file: "characters/player_boy/side.png", label: "side", required: true },
            { file: "characters/player_boy/back.png", label: "back", required: true },
            { file: "characters/player_boy/three_quarter.png", label: "¾", required: true },
            { file: "characters/player_boy/expressions.png", label: "expressions" },
          ],
        },
      ],
    },
    {
      id: "animals",
      title: "Animals",
      intro: "Turnaround sheet required before modelling. The 10 start-mission animals are a proposal (Q-002).",
      items: [
        {
          id: "zebra",
          title: "Zebra",
          status: "planned",
          description: "Start mission animal (CONT-MISSIONS), hides at: river (drinking).",
          spec: "ART-ANIMALS",
          images: [
            { file: "animals/zebra/front.png", label: "front", required: true },
            { file: "animals/zebra/side.png", label: "side", required: true },
            { file: "animals/zebra/back.png", label: "back", required: true },
            { file: "animals/zebra/three_quarter.png", label: "¾", required: true },
          ],
        },
        {
          id: "hippo",
          title: "Flusspferd / hippo",
          status: "planned",
          description: "Start mission animal (CONT-MISSIONS), hides at: pond.",
          spec: "ART-ANIMALS",
          images: [
            { file: "animals/hippo/front.png", label: "front", required: true },
            { file: "animals/hippo/side.png", label: "side", required: true },
            { file: "animals/hippo/back.png", label: "back", required: true },
            { file: "animals/hippo/three_quarter.png", label: "¾", required: true },
          ],
        },
        {
          id: "panda",
          title: "Panda",
          status: "planned",
          description: "Start mission animal (CONT-MISSIONS), hides at: cave.",
          spec: "ART-ANIMALS",
          images: [
            { file: "animals/panda/front.png", label: "front", required: true },
            { file: "animals/panda/side.png", label: "side", required: true },
            { file: "animals/panda/back.png", label: "back", required: true },
            { file: "animals/panda/three_quarter.png", label: "¾", required: true },
          ],
        },
        {
          id: "koala",
          title: "Koala",
          status: "planned",
          description: "Start mission animal (CONT-MISSIONS), hides at: tallest tree.",
          spec: "ART-ANIMALS",
          images: [
            { file: "animals/koala/front.png", label: "front", required: true },
            { file: "animals/koala/side.png", label: "side", required: true },
            { file: "animals/koala/back.png", label: "back", required: true },
            { file: "animals/koala/three_quarter.png", label: "¾", required: true },
          ],
        },
        {
          id: "elephant",
          title: "Elefant / elephant",
          status: "planned",
          description: "Start mission animal (CONT-MISSIONS), hides at: mud pool.",
          spec: "ART-ANIMALS",
          images: [
            { file: "animals/elephant/front.png", label: "front", required: true },
            { file: "animals/elephant/side.png", label: "side", required: true },
            { file: "animals/elephant/back.png", label: "back", required: true },
            { file: "animals/elephant/three_quarter.png", label: "¾", required: true },
          ],
        },
        {
          id: "goldfish",
          title: "Goldfisch / goldfish",
          status: "planned",
          description: "Start mission animal (CONT-MISSIONS), hides at: fountain.",
          spec: "ART-ANIMALS",
          images: [
            { file: "animals/goldfish/front.png", label: "front", required: true },
            { file: "animals/goldfish/side.png", label: "side", required: true },
            { file: "animals/goldfish/back.png", label: "back", required: true },
            { file: "animals/goldfish/three_quarter.png", label: "¾", required: true },
          ],
        },
        {
          id: "monkey",
          title: "Affe / monkey",
          status: "planned",
          description: "Start mission animal (CONT-MISSIONS), hides at: pirate ship.",
          spec: "ART-ANIMALS",
          images: [
            { file: "animals/monkey/front.png", label: "front", required: true },
            { file: "animals/monkey/side.png", label: "side", required: true },
            { file: "animals/monkey/back.png", label: "back", required: true },
            { file: "animals/monkey/three_quarter.png", label: "¾", required: true },
          ],
        },
        {
          id: "giraffe",
          title: "Giraffe",
          status: "planned",
          description: "Start mission animal (CONT-MISSIONS), hides at: playground.",
          spec: "ART-ANIMALS",
          images: [
            { file: "animals/giraffe/front.png", label: "front", required: true },
            { file: "animals/giraffe/side.png", label: "side", required: true },
            { file: "animals/giraffe/back.png", label: "back", required: true },
            { file: "animals/giraffe/three_quarter.png", label: "¾", required: true },
          ],
        },
        {
          id: "lion",
          title: "Löwe / lion",
          status: "planned",
          description: "Start mission animal (CONT-MISSIONS), hides at: sun rocks.",
          spec: "ART-ANIMALS",
          images: [
            { file: "animals/lion/front.png", label: "front", required: true },
            { file: "animals/lion/side.png", label: "side", required: true },
            { file: "animals/lion/back.png", label: "back", required: true },
            { file: "animals/lion/three_quarter.png", label: "¾", required: true },
          ],
        },
        {
          id: "snow_fox",
          title: "Schneefuchs / snow fox",
          status: "planned",
          description: "Start mission animal (CONT-MISSIONS), hides at: ice cream kiosk.",
          spec: "ART-ANIMALS",
          images: [
            { file: "animals/snow_fox/front.png", label: "front", required: true },
            { file: "animals/snow_fox/side.png", label: "side", required: true },
            { file: "animals/snow_fox/back.png", label: "back", required: true },
            { file: "animals/snow_fox/three_quarter.png", label: "¾", required: true },
          ],
        },
      ],
    },
    {
      id: "environment",
      title: "Environment",
      intro: "Mockups required before building an area: overview (elevated ¾) and player view (third-person camera height), plus layout.md.",
      items: [],
    },
  ],
};
