// Art review catalog — rendered by art/index.html.
// Plain JS (not JSON) so the page works when opened directly from disk (file://).
// Paths are relative to art/. Status values: planned | brief | in-review | changes-requested | approved.
// "approved" must match concept_approved = true in assets/manifest.toml (ART-PIPELINE).
window.ART_CATALOG = {
  updated: "2026-09-26",
  sections: [
    {
      id: "reference",
      title: "Reference",
      intro: "External reference images for content and layout ideas (enclosures, signs, zoo layout). Not our own assets. The art style is NOT taken from these — it is comic, see art/style/style.md.",
      items: [
        {
          id: "ref_player_farm",
          title: "Player character style",
          status: "reference",
          description: "Girl in a striped shirt walking with a bear, sheep and chick. Reference for the player character's outfit and proportions only — not the voxel style.",
          spec: "ART-DIRECTION",
          images: [{ file: "reference/ref-player-style.jpg", label: "reference" }],
        },
        {
          id: "ref_enclosure_row",
          title: "Enclosure row with signs",
          status: "reference",
          description: "Row of enclosures with signs showing the animal name and a silhouette, wooden fences, open grass field with hippos, zebras and a snow fox.",
          spec: "ART-DIRECTION",
          images: [{ file: "reference/ref-enclosure-row.jpg", label: "reference" }],
        },
        {
          id: "ref_enclosure_buildings",
          title: "Distinct enclosure buildings",
          status: "reference",
          description: "Each animal has a recognisable building: wooden hut (hippo), stone arch (zebra), glass house (snow fox). Large readable wooden signs.",
          spec: "ART-DIRECTION",
          images: [{ file: "reference/ref-enclosure-buildings.jpg", label: "reference" }],
        },
        {
          id: "ref_zoo_layout",
          title: "Zoo layout and camera",
          status: "reference",
          description: "Isometric zoo with paths, kiosks and props. Reference for the high-angle zoo-park camera and zoo layout — not for the style (style is comic, art/style/style.md).",
          spec: "ART-DIRECTION",
          images: [{ file: "reference/ref-zoo-layout.webp", label: "reference" }],
        },
      ],
    },
    {
      id: "characters",
      title: "Characters",
      intro: "Human characters. Turnaround sheet required before modelling: front, side, back, ¾.",
      items: [
        {
          id: "player_girl",
          title: "Player — girl",
          status: "approved",
          description: "Playable girl, ~6–8 years old, comic style; hair, clothes and colours from the reference image.",
          spec: "ART-CHARACTERS",
          brief: "characters/player_girl/brief.md",
          notes: "Proposal: 1.20 m, head-to-body 1 : 3.5, long dark-brown hair, white/blue striped shirt, jeans. Rig and animations: ART-RIG. Generated with gemini-3-pro-image as one turnaround sheet (sheet_v1, split into the four views); sheet_v2 is an alternative.",
          images: [
            { file: "characters/player_girl/front.png", label: "front", required: true },
            { file: "characters/player_girl/side.png", label: "side", required: true },
            { file: "characters/player_girl/back.png", label: "back", required: true },
            { file: "characters/player_girl/three_quarter.png", label: "¾", required: true },
            { file: "characters/player_girl/expressions.png", label: "expressions (chosen = expressions_v1)" },
            { file: "characters/player_girl/expressions_v2.jpg", label: "expressions v2 (alternative)" },
            { file: "characters/player_girl/sheet_v1.jpg", label: "sheet_v1 (source)" },
            { file: "characters/player_girl/sheet_v2.jpg", label: "sheet_v2 (alternative)" },
            { file: "characters/player_girl/model_preview.png", label: "3D model preview" },
          ],
        },
        {
          id: "player_boy",
          title: "Player — boy",
          status: "approved",
          description: "Playable boy, matching counterpart to the girl, same rig and proportions.",
          spec: "ART-CHARACTERS",
          brief: "characters/player_boy/brief.md",
          notes: "New design, please review: short chestnut hair with a tuft, mustard-yellow shirt with a green band, navy shorts, green sneakers. Generated with gemini-3-pro-image as one turnaround sheet in the girl's style (sheet_v2, split; side view mirrored to face left); sheet_v1 is an alternative without the hair tuft.",
          images: [
            { file: "characters/player_boy/front.png", label: "front", required: true },
            { file: "characters/player_boy/side.png", label: "side", required: true },
            { file: "characters/player_boy/back.png", label: "back", required: true },
            { file: "characters/player_boy/three_quarter.png", label: "¾", required: true },
            { file: "characters/player_boy/expressions.png", label: "expressions (chosen = expressions_v2)" },
            { file: "characters/player_boy/expressions_v1.jpg", label: "expressions v1 (alternative)" },
            { file: "characters/player_boy/sheet_v2.jpg", label: "sheet_v2 (source)" },
            { file: "characters/player_boy/sheet_v1.jpg", label: "sheet_v1 (alternative)" },
          ],
        },
      ],
    },
    {
      id: "animals",
      title: "Animals",
      intro: "Turnaround sheet required before modelling. The 10 start-mission animals are a proposal (Q-002). Size check: animals/lineup.png (all front views + the 1.2 m girl at their intended relative heights).",
      items: [
        {
          id: "zebra",
          title: "Zebra",
          status: "approved",
          description: "Start mission animal (CONT-MISSIONS), hides at: river (drinking).",
          spec: "ART-ANIMALS",
          brief: "animals/zebra/brief.md",
          notes: "Generated with gemini-3-pro-image from one turnaround sheet (sheet_v1, split into the four views) for consistent angles. sheet_v2 is an alternative.",
          images: [
            { file: "animals/zebra/front.png", label: "front", required: true },
            { file: "animals/zebra/side.png", label: "side", required: true },
            { file: "animals/zebra/back.png", label: "back", required: true },
            { file: "animals/zebra/three_quarter.png", label: "¾", required: true },
            { file: "animals/zebra/sheet_v1.jpg", label: "sheet v1 (source)" },
            { file: "animals/zebra/sheet_v2.jpg", label: "sheet v2 (alternative)" },
            { file: "animals/zebra/model_preview.png", label: "3D model preview" },
          ],
        },
        {
          id: "hippo",
          title: "Flusspferd / hippo",
          status: "approved",
          description: "Start mission animal (CONT-MISSIONS), hides at: pond.",
          spec: "ART-ANIMALS",
          brief: "animals/hippo/brief.md",
          notes: "Chosen sheet_v1 (clean side profile); sheet_v2 alternative (side slightly turned). Back height ≈ 1.4 m.",
          images: [
            { file: "animals/hippo/front.png", label: "front", required: true },
            { file: "animals/hippo/side.png", label: "side", required: true },
            { file: "animals/hippo/back.png", label: "back", required: true },
            { file: "animals/hippo/three_quarter.png", label: "¾", required: true },
            { file: "animals/hippo/sheet_v1.jpg", label: "sheet v1 (chosen, source)" },
            { file: "animals/hippo/sheet_v2.jpg", label: "sheet v2 (alternative)" },
          ],
        },
        {
          id: "panda",
          title: "Panda",
          status: "approved",
          description: "Start mission animal (CONT-MISSIONS), hides at: cave.",
          spec: "ART-ANIMALS",
          brief: "animals/panda/brief.md",
          notes: "Chosen sheet_v2; sheet_v1 alternative (side/¾ face right, weaker back view). Back ≈ 0.85 m on all fours.",
          images: [
            { file: "animals/panda/front.png", label: "front", required: true },
            { file: "animals/panda/side.png", label: "side", required: true },
            { file: "animals/panda/back.png", label: "back", required: true },
            { file: "animals/panda/three_quarter.png", label: "¾", required: true },
            { file: "animals/panda/sheet_v2.jpg", label: "sheet v2 (chosen, source)" },
            { file: "animals/panda/sheet_v1.jpg", label: "sheet v1 (alternative)" },
          ],
        },
        {
          id: "koala",
          title: "Koala",
          status: "approved",
          description: "Start mission animal (CONT-MISSIONS), hides at: tallest tree.",
          spec: "ART-ANIMALS",
          brief: "animals/koala/brief.md",
          notes: "DECISION: chosen sheet_v3 = on all fours (fits the quadruped rig, can follow on foot); sheet_v2 = alternative upright teddy pose (needs its own rig, Q-043). side.png head redrawn in edit mode (original side head was turned away). Back ≈ 0.45 m, very small next to the girl.",
          images: [
            { file: "animals/koala/front.png", label: "front", required: true },
            { file: "animals/koala/side.png", label: "side", required: true },
            { file: "animals/koala/back.png", label: "back", required: true },
            { file: "animals/koala/three_quarter.png", label: "¾", required: true },
            { file: "animals/koala/sheet_v3.jpg", label: "sheet v3 (chosen, source)" },
            { file: "animals/koala/sheet_v2.jpg", label: "sheet v2 (alternative)" },
          ],
        },
        {
          id: "zebra_female",
          title: "Zebra \u2014 female (pair)",
          status: "in-review",
          description: "Female partner of the zebra (GAME-FAMILY pair; the existing zebra art = the male). ~10 % smaller, soft forelock falling forward over the forehead, eyelashes.",
          spec: "GAME-FAMILY",
          brief: "animals/zebra_female/brief.md",
          notes: "Q-074 proposal applied (forelock + size). Chosen sheet_v2 (split); v1 was deleted. Compare in animals/zebra_family.png (FAM-007).",
          images: [
            { file: "animals/zebra_female/front.png", label: "front", required: true },
            { file: "animals/zebra_female/side.png", label: "side", required: true },
            { file: "animals/zebra_female/back.png", label: "back", required: true },
            { file: "animals/zebra_female/three_quarter.png", label: "\u00be", required: true },
            { file: "animals/zebra_female/sheet_v2.jpg", label: "sheet v2 (chosen, source)" },
          ],
        },
        {
          id: "zebra_foal",
          title: "Zebra foal (baby)",
          status: "in-review",
          description: "Baby of the zebra pair (Fohlen / foal, GAME-FAMILY): long thin legs, big head and eyes, fluffy mane; ~45\u201350 % of the male.",
          spec: "GAME-FAMILY",
          brief: "animals/zebra_foal/brief.md",
          notes: "Chosen sheet_v2 (split); v1 was deleted (side view faced right).",
          images: [
            { file: "animals/zebra_foal/front.png", label: "front", required: true },
            { file: "animals/zebra_foal/side.png", label: "side", required: true },
            { file: "animals/zebra_foal/back.png", label: "back", required: true },
            { file: "animals/zebra_foal/three_quarter.png", label: "\u00be", required: true },
            { file: "animals/zebra_foal/sheet_v2.jpg", label: "sheet v2 (chosen, source)" },
          ],
        },
        {
          id: "koala_female",
          title: "Koala \u2014 female (pair)",
          status: "in-review",
          description: "Female partner of the koala (GAME-FAMILY pair; the existing koala art = the male). Slightly smaller, lighter silvery fur, eyelashes.",
          spec: "GAME-FAMILY",
          brief: "animals/koala_female/brief.md",
          notes: "Chosen sheet_v5 (edit of an edit, see log); v6 alternative. Known issue: the cream chest patch is only a little larger than the male's \u2014 the visible differences are lighter fur, eyelashes and size (decide in Q-074). Split with split_sheet.py --equal (ears overlap).",
          images: [
            { file: "animals/koala_female/front.png", label: "front", required: true },
            { file: "animals/koala_female/side.png", label: "side", required: true },
            { file: "animals/koala_female/back.png", label: "back", required: true },
            { file: "animals/koala_female/three_quarter.png", label: "\u00be", required: true },
            { file: "animals/koala_female/sheet_v5.jpg", label: "sheet v5 (chosen, source)" },
            { file: "animals/koala_female/sheet_v6.jpg", label: "sheet v6 (alternative)" },
          ],
        },
        {
          id: "koala_joey",
          title: "Koala joey (baby)",
          status: "in-review",
          description: "Baby of the koala pair (Koalababy / joey, GAME-FAMILY): tiny body, extra big head and ears, huge eyes, on all fours; ~45 % of the male.",
          spec: "GAME-FAMILY",
          brief: "animals/koala_joey/brief.md",
          notes: "Chosen sheet_v3; sheet_v1 alternative (less baby-like). Split with --equal.",
          images: [
            { file: "animals/koala_joey/front.png", label: "front", required: true },
            { file: "animals/koala_joey/side.png", label: "side", required: true },
            { file: "animals/koala_joey/back.png", label: "back", required: true },
            { file: "animals/koala_joey/three_quarter.png", label: "\u00be", required: true },
            { file: "animals/koala_joey/sheet_v3.jpg", label: "sheet v3 (chosen, source)" },
            { file: "animals/koala_joey/sheet_v1.jpg", label: "sheet v1 (alternative)" },
          ],
        },
        {
          id: "zebra_family",
          title: "Zebra family lineup",
          status: "in-review",
          description: "Male (100 %), female (91 %) and foal (50 %) side by side, \u00be views scaled by figure height \u2014 for FAM-007 (can children tell the pair apart?).",
          spec: "GAME-FAMILY",
          notes: "Composite of the \u00be views (no generation).",
          images: [
            { file: "animals/zebra_family.png", label: "zebra family", required: true },
          ],
        },
        {
          id: "koala_family",
          title: "Koala family lineup",
          status: "in-review",
          description: "Male (100 %), female (92 %) and joey (46 %) side by side, \u00be views scaled by figure height \u2014 for FAM-007.",
          spec: "GAME-FAMILY",
          notes: "Composite of the \u00be views (no generation).",
          images: [
            { file: "animals/koala_family.png", label: "koala family", required: true },
          ],
        },
        {
          id: "elephant",
          title: "Elefant / elephant",
          status: "approved",
          description: "Start mission animal (CONT-MISSIONS), hides at: mud pool.",
          spec: "ART-ANIMALS",
          brief: "animals/elephant/brief.md",
          notes: "Chosen sheet_v1; sheet_v2 alternative (slightly open mouth in ¾). No tusks. Back ≈ 2.5 m.",
          images: [
            { file: "animals/elephant/front.png", label: "front", required: true },
            { file: "animals/elephant/side.png", label: "side", required: true },
            { file: "animals/elephant/back.png", label: "back", required: true },
            { file: "animals/elephant/three_quarter.png", label: "¾", required: true },
            { file: "animals/elephant/sheet_v1.jpg", label: "sheet v1 (chosen, source)" },
            { file: "animals/elephant/sheet_v2.jpg", label: "sheet v2 (alternative)" },
          ],
        },
        {
          id: "goldfish",
          title: "Goldfisch / goldfish",
          status: "approved",
          description: "Start mission animal (CONT-MISSIONS), hides at: fountain.",
          spec: "ART-ANIMALS",
          brief: "animals/goldfish/brief.md",
          notes: "Views adapted (proposal): side, top, front, ¾ — swimming pose, no legs; top view = in-game view. No alternative sheet: three other attempts failed (zebra legs leaked from the reference sheet, or the style frame was returned). ≈ 0.3 m long.",
          images: [
            { file: "animals/goldfish/side.png", label: "side", required: true },
            { file: "animals/goldfish/top.png", label: "top", required: true },
            { file: "animals/goldfish/front.png", label: "front", required: true },
            { file: "animals/goldfish/three_quarter.png", label: "¾", required: true },
            { file: "animals/goldfish/sheet_v2.jpg", label: "sheet v2 (chosen, source)" },
          ],
        },
        {
          id: "monkey",
          title: "Affe / monkey",
          status: "approved",
          description: "Start mission animal (CONT-MISSIONS), hides at: pirate ship.",
          spec: "ART-ANIMALS",
          brief: "animals/monkey/brief.md",
          notes: "DECISION: drawn upright on two feet (biped rig, not quadruped — Q-043). Chosen sheet_v2 (spiral tail visible in all views); sheet_v1 alternative. baby_sheet_v2 = baby proposal (Q-040, not split). Height ≈ 0.9 m.",
          images: [
            { file: "animals/monkey/front.png", label: "front", required: true },
            { file: "animals/monkey/side.png", label: "side", required: true },
            { file: "animals/monkey/back.png", label: "back", required: true },
            { file: "animals/monkey/three_quarter.png", label: "¾", required: true },
            { file: "animals/monkey/sheet_v2.jpg", label: "sheet v2 (chosen, source)" },
            { file: "animals/monkey/sheet_v1.jpg", label: "sheet v1 (alternative)" },
            { file: "animals/monkey/baby_sheet_v2.jpg", label: "baby sheet (Q-040 proposal)" },
          ],
        },
        {
          id: "giraffe",
          title: "Giraffe",
          status: "approved",
          description: "Start mission animal (CONT-MISSIONS), hides at: playground.",
          spec: "ART-ANIMALS",
          brief: "animals/giraffe/brief.md",
          notes: "Chosen sheet_v1 (few large patches, reads at 60 px); sheet_v2 alternative (many smaller spots). Neck is rather short/foal-like — top of head 4.5 m in the lineup.",
          images: [
            { file: "animals/giraffe/front.png", label: "front", required: true },
            { file: "animals/giraffe/side.png", label: "side", required: true },
            { file: "animals/giraffe/back.png", label: "back", required: true },
            { file: "animals/giraffe/three_quarter.png", label: "¾", required: true },
            { file: "animals/giraffe/sheet_v1.jpg", label: "sheet v1 (chosen, source)" },
            { file: "animals/giraffe/sheet_v2.jpg", label: "sheet v2 (alternative)" },
          ],
        },
        {
          id: "lion",
          title: "Löwe / lion",
          status: "approved",
          description: "Start mission animal (CONT-MISSIONS), hides at: sun rocks.",
          spec: "ART-ANIMALS",
          brief: "animals/lion/brief.md",
          notes: "Chosen sheet_v1 (mane in few big tufts); sheet_v2 alternative (strand-detailed mane). Back ≈ 1.1 m.",
          images: [
            { file: "animals/lion/front.png", label: "front", required: true },
            { file: "animals/lion/side.png", label: "side", required: true },
            { file: "animals/lion/back.png", label: "back", required: true },
            { file: "animals/lion/three_quarter.png", label: "¾", required: true },
            { file: "animals/lion/sheet_v1.jpg", label: "sheet v1 (chosen, source)" },
            { file: "animals/lion/sheet_v2.jpg", label: "sheet v2 (alternative)" },
          ],
        },
        {
          id: "snow_fox",
          title: "Schneefuchs / snow fox",
          status: "approved",
          description: "Start mission animal (CONT-MISSIONS), hides at: ice cream kiosk.",
          spec: "ART-ANIMALS",
          brief: "animals/snow_fox/brief.md",
          notes: "Chosen sheet_v2; sheet_v1 alternative (back view is an unreadable white blob). Note: tail is up in side/¾ but hangs in the back view — align when modelling. Back ≈ 0.4 m.",
          images: [
            { file: "animals/snow_fox/front.png", label: "front", required: true },
            { file: "animals/snow_fox/side.png", label: "side", required: true },
            { file: "animals/snow_fox/back.png", label: "back", required: true },
            { file: "animals/snow_fox/three_quarter.png", label: "¾", required: true },
            { file: "animals/snow_fox/sheet_v2.jpg", label: "sheet v2 (chosen, source)" },
            { file: "animals/snow_fox/sheet_v1.jpg", label: "sheet v1 (alternative)" },
          ],
        },
        {
          id: "animals_lineup",
          title: "Lineup — all animals + girl (size check)",
          status: "in-review",
          description: "Front views of all 10 animals and the player girl, scaled to their intended heights (top of head/ears): girl 1.2, zebra 2.23, hippo 1.7, panda 1.1, koala 0.65, elephant 3.0, goldfish 0.16 (0.3 long), monkey 0.9, giraffe 4.5, lion 1.5, snow fox 0.6 m.",
          spec: "ART-ANIMALS",
          notes: "Decide whether the small animals (koala, snow fox, monkey, goldfish) should be scaled up for readability from the 55° camera.",
          images: [
            { file: "animals/lineup.png", label: "lineup", required: true },
          ],
        },
      ],
    },
    {
      id: "environment",
      title: "Environment",
      intro: "Mockups required before building an area: overview (high ¾ view, ~60–65°) and player view (in-game high-angle follow camera, ~55°, zoo-park-simulation style — Q-049), plus layout.md. Start with the style frame (Q-010).",
      items: [
        {
          id: "style_frame",
          title: "Style frame — comic style",
          status: "approved",
          description: "One comic-style image of the zebra-enclosure scene from the high game camera. Once approved, it is the style reference for all concept images (art/style/style.md).",
          spec: "ART-ENVIRONMENT",
          brief: "environment/style_frame/brief.md",
          notes: "Approved 2026-09-26: variant 3 (copied to style_frame.png) — the style reference for all concept images. Generated with gemini-3-pro-image (1K, 16:9). Known deviations: the girl is much larger than 1/12 of the image height; v1/v2 enclosure silhouettes look like a horse (no stripes); v2 has a pond inside the zebra enclosure (not allowed).",
          images: [
            { file: "environment/style_frame/style_frame_v1.jpg", label: "variant 1 (Gemini)" },
            { file: "environment/style_frame/style_frame_v2.jpg", label: "variant 2 (Gemini)" },
            { file: "environment/style_frame/style_frame_v3.jpg", label: "variant 3 (Gemini)" },
            { file: "environment/style_frame/style_frame.png", label: "approved (= variant 3)", required: true },
          ],
        },
        {
          id: "env_level1_overview",
          title: "Level 1 — bird's-eye overview",
          status: "in-review",
          description: "Whole level 1 as a diorama: entrance, food storage, ring path around a tree grove, zebra/hippo/panda enclosures, river, pond, cave, barriers.",
          spec: "GAME-LEVEL-1",
          brief: "environment/env_level1_overview/brief.md",
          notes: "Chosen overview_v1 (layout matches the map well; entrance is a plain stone arch, cave faces the entrance instead of north). top_down_v1 chosen (animals shown at home \u2014 fine for the map board). Level layout may still change (more hiding places being added).",
          images: [
            { file: "environment/env_level1_overview/overview.png", label: "overview (chosen v1)", required: true },
            { file: "environment/env_level1_overview/top_down.png", label: "top-down (chosen v1)", required: true },
            { file: "environment/env_level1_overview/overview_v2.jpg", label: "overview v2 (alternative)" },
            { file: "environment/env_level1_overview/top_down_v2.jpg", label: "top-down v2 (alternative)" },
          ],
        },
        {
          id: "env_entrance",
          title: "Zoo entrance (level 1)",
          status: "in-review",
          description: "Spawn point: entrance arch, plaza, picture map board, bench; food storage straight ahead, zebra fence left, rock hill right.",
          spec: "ART-ENVIRONMENT",
          brief: "environment/env_entrance/brief.md",
          notes: "Chosen overview_v2 / player_view_v1. Issues: two visitor figures appear; the cave mouth is visible from the plaza (should face north). Level layout may still change.",
          images: [
            { file: "environment/env_entrance/overview.png", label: "overview (chosen v2)", required: true },
            { file: "environment/env_entrance/player_view.png", label: "player view 9:16 (chosen v1)", required: true },
            { file: "environment/env_entrance/overview_v1.jpg", label: "overview v1 (alternative)" },
            { file: "environment/env_entrance/player_view_v2.jpg", label: "player view v2 (alternative)" },
          ],
        },
        {
          id: "env_food_storage",
          title: "Food storage (level 1)",
          status: "in-review",
          description: "Wooden barn in the middle of the ring with an open double door and 10 closed food boxes with blank label panels.",
          spec: "ART-ENVIRONMENT",
          brief: "environment/env_food_storage/brief.md",
          notes: "Chosen overview_v2 / player_view_v1 (interior with the roof removed, crates with blank labels \u2014 labels on the lids). Level layout may still change.",
          images: [
            { file: "environment/env_food_storage/overview.png", label: "overview (chosen v2)", required: true },
            { file: "environment/env_food_storage/player_view.png", label: "player view 9:16 (chosen v1)", required: true },
            { file: "environment/env_food_storage/overview_v1.jpg", label: "overview v1 (alternative)" },
            { file: "environment/env_food_storage/player_view_v2.jpg", label: "player view v2 (alternative)" },
          ],
        },
        {
          id: "env_zebra",
          title: "Zebra enclosure (level 1)",
          status: "in-review",
          description: "Empty zebra enclosure: grass, bushes, stone arch shelter; gate with silhouette sign and blank info board.",
          spec: "ART-ENVIRONMENT",
          brief: "environment/env_zebra/brief.md",
          notes: "Chosen overview_v2 (striped zebra-head silhouette) / player_view_v1. overview_v1 silhouette reads as a horse. Girl larger than 1/12 in the player view. No water in the enclosure. Level layout may still change.",
          images: [
            { file: "environment/env_zebra/overview.png", label: "overview (chosen v2)", required: true },
            { file: "environment/env_zebra/player_view.png", label: "player view 9:16 (chosen v1)", required: true },
            { file: "environment/env_zebra/overview_v1.jpg", label: "overview v1 (alternative)" },
            { file: "environment/env_zebra/player_view_v2.jpg", label: "player view v2 (alternative)" },
          ],
        },
        {
          id: "env_hippo",
          title: "Hippo enclosure (level 1)",
          status: "in-review",
          description: "Empty hippo enclosure: square tiled pool, stones, wooden hut; gate framed by tall hedges; river bend behind.",
          spec: "ART-ENVIRONMENT",
          brief: "environment/env_hippo/brief.md",
          notes: "Chosen overview_v2 / player_view_v2. Generator added mud patches (not specified). Pool square and tiled, no lilies. Level layout may still change.",
          images: [
            { file: "environment/env_hippo/overview.png", label: "overview (chosen v2)", required: true },
            { file: "environment/env_hippo/player_view.png", label: "player view 9:16 (chosen v2)", required: true },
            { file: "environment/env_hippo/overview_v1.jpg", label: "overview v1 (alternative)" },
            { file: "environment/env_hippo/player_view_v1.jpg", label: "player view v1 (alternative)" },
          ],
        },
        {
          id: "env_panda",
          title: "Panda enclosure (level 1)",
          status: "in-review",
          description: "Empty panda enclosure: bamboo, wooden platform and shelter; side path to the closed north gate; river and bridge to the east.",
          spec: "ART-ENVIRONMENT",
          brief: "environment/env_panda/brief.md",
          notes: "Chosen overview_v2 / player_view_v2. Both show growing bamboo inside \u2014 GAME-LEVEL-1 now proposes cut bamboo on a feeding rack only (growing bamboo only at loc_bamboo); player view also shows the rack. Wood only, no stone. Level layout may still change.",
          images: [
            { file: "environment/env_panda/overview.png", label: "overview (chosen v2)", required: true },
            { file: "environment/env_panda/player_view.png", label: "player view 9:16 (chosen v2)", required: true },
            { file: "environment/env_panda/overview_v1.jpg", label: "overview v1 (alternative)" },
            { file: "environment/env_panda/player_view_v1.jpg", label: "player view v1 (alternative)" },
          ],
        },
        {
          id: "loc_river",
          title: "River — zebra hiding place",
          status: "in-review",
          description: "Flowing river with rapids, wooden bridge, ducks; zebras drinking on the bank; fallen-tree barrier behind the bridge.",
          spec: "ART-ENVIRONMENT",
          brief: "environment/loc_river/brief.md",
          notes: "Chosen overview_v2 / player_view_v1. Stray enclosure-style signs near the river in some images (ignore). Level layout may still change.",
          images: [
            { file: "environment/loc_river/overview.png", label: "overview (chosen v2)", required: true },
            { file: "environment/loc_river/player_view.png", label: "player view 9:16 (chosen v1)", required: true },
            { file: "environment/loc_river/overview_v1.jpg", label: "overview v1 (alternative)" },
            { file: "environment/loc_river/player_view_v2.jpg", label: "player view v2 (alternative)" },
          ],
        },
        {
          id: "loc_pond",
          title: "Pond — hippo hiding place",
          status: "in-review",
          description: "Round still pond with water lilies, frogs, reeds and a jetty; hippo with only eyes and ears above water.",
          spec: "ART-ENVIRONMENT",
          brief: "environment/loc_pond/brief.md",
          notes: "Chosen overview_v2 / player_view_v2. A stray hippo sign on the pond shore in the overview (the pond is not an enclosure). Level layout may still change.",
          images: [
            { file: "environment/loc_pond/overview.png", label: "overview (chosen v2)", required: true },
            { file: "environment/loc_pond/player_view.png", label: "player view 9:16 (chosen v2)", required: true },
            { file: "environment/loc_pond/overview_v1.jpg", label: "overview v1 (alternative)" },
            { file: "environment/loc_pond/player_view_v1.jpg", label: "player view v1 (alternative)" },
          ],
        },
        {
          id: "loc_cave",
          title: "Cave — panda hiding place",
          status: "in-review",
          description: "Grey rock hill with a dark, cool cave mouth facing north; panda asleep inside; 'path under repair' barrier on the service path.",
          spec: "ART-ENVIRONMENT",
          brief: "environment/loc_cave/brief.md",
          notes: "Chosen overview_v2 (shows the cutaway state, roof removed) / player_view_v1 (closed hill, panda in the dark mouth; stray panda sign beside the cave). Level layout may still change.",
          images: [
            { file: "environment/loc_cave/overview.png", label: "overview (chosen v2)", required: true },
            { file: "environment/loc_cave/player_view.png", label: "player view 9:16 (chosen v1)", required: true },
            { file: "environment/loc_cave/overview_v1.jpg", label: "overview v1 (alternative)" },
            { file: "environment/loc_cave/player_view_v2.jpg", label: "player view v2 (alternative)" },
          ],
        },
        {
          id: "water_anim",
          title: "Animated water (prototype)",
          status: "in-review",
          description: "Shader prototype for living water (ART-ENVIRONMENT rule 5): 3-wide river with a bend, bridge and rock next to a round pond with lily pads, from the 55° game camera. River: hard-edged light streaks and white flecks scroll along the flow (also around the bend), foam at banks and around the rock. Pond: expanding rings, twinkling light dashes and glints in place — no direction. Ducks and lily pads bob.",
          spec: "TECH-WATER",
          notes: "Rendered headless from web/prototypes/water.html (raw WebGL2, palette colours, ?t= freezes time, ?mode=1/2 alternatives). Variants image: recommended | world bands (seam at the bend) | per-tile scroll (1 m repeat, tile seams). Review: does the river read as flowing and the pond as still? (AENV-009)",
          images: [
            { file: "environment/water/water_loop.gif", label: "animated, 4 s (d = 14 m)" },
            { file: "environment/water/water_t0.0.png", label: "t = 0.0 s" },
            { file: "environment/water/water_t0.5.png", label: "t = 0.5 s" },
            { file: "environment/water/water_t1.0.png", label: "t = 1.0 s" },
            { file: "environment/water/water_zoom20_t1.0.png", label: "zoomed out (d = 20 m)" },
            { file: "environment/water/water_variants.png", label: "variants: recommended | bands | tile scroll" },
          ],
        },
      ],
    },
    {
      id: "props",
      title: "Props (modular kits)",
      intro: "Modular props modelled once and reused, generated as asset sheets from the same high camera angle. Budget ≤ 500 triangles each.",
      items: [
        {
          id: "kit_ground",
          title: "Kit 1 — ground and paths",
          status: "approved",
          description: "Floor tiles: path straight/curve/T/cross/end, plaza, grass, path edge, sand.",
          spec: "ART-ENVIRONMENT",
          brief: "props/kit_ground/brief.md",
          notes: "Chosen v2 (correct T-junction). v1 is an alternative. Generated with gemini-3-pro-image (2K, 16:9).",
          images: [
            { file: "props/kit_ground/sheet_v2.jpg", label: "sheet_v2 (chosen)", required: true },
            { file: "props/kit_ground/sheet_v1.jpg", label: "sheet_v1 (alternative)" },
            { file: "props/kit_ground/model_preview.png", label: "3D model preview" },
          ],
        },
        {
          id: "kit_fences",
          title: "Kit 2 — fences, gates, hedges, walls",
          status: "approved",
          description: "Wooden post-and-rail fence, gate (closed/open), tall hedge, outer zoo wall — with corners.",
          spec: "ART-ENVIRONMENT",
          brief: "props/kit_fences/brief.md",
          notes: "Chosen v3 = v2 edited so the end post is a single post. Generated with gemini-3-pro-image (2K, 16:9).",
          images: [
            { file: "props/kit_fences/sheet_v3.jpg", label: "sheet_v3 (chosen)", required: true },
            { file: "props/kit_fences/sheet_v1.jpg", label: "sheet_v1 (alternative)" },
            { file: "props/kit_fences/model_preview.png", label: "3D model preview" },
          ],
        },
        {
          id: "kit_signs",
          title: "Kit 3 — signs, boards, food boxes",
          status: "approved",
          description: "Enclosure sign (blank, silhouette slot), info board, map board, food box, stack of food boxes — all blank.",
          spec: "ART-ENVIRONMENT",
          brief: "props/kit_signs/brief.md",
          notes: "Chosen v5 = v4 edited so the enclosure sign panel leans back towards the high camera. Generated with gemini-3-pro-image (2K, 16:9).",
          images: [
            { file: "props/kit_signs/sheet_v5.jpg", label: "sheet_v5 (chosen)", required: true },
            { file: "props/kit_signs/sheet_v3.jpg", label: "sheet_v3 (alternative)" },
            { file: "props/kit_signs/model_preview.png", label: "3D model preview" },
          ],
        },
        {
          id: "sign_silhouettes",
          title: "Enclosure sign silhouettes",
          status: "in-review",
          description: "Solid dark (#2B2320) animal silhouettes on transparent background, drawn by the renderer as a decal on the cream enclosure_sign panel (ART-ENVIRONMENT behaviour 6, AENV-011). Zebra: side view facing left with mohawk mane, ear, tufted tail and stripe cut-outs so it reads as a zebra, not a horse.",
          spec: "ART-ENVIRONMENT",
          notes: "Generated procedurally by tools/textures/sign_silhouettes.py (source of truth, 384×256 PNG), modelled on animals/zebra/side.png. The other animals' silhouettes are derived from their concept side views by the same script.",
          images: [{ file: "../assets/textures/signs/silhouette_zebra.png", label: "zebra", required: true }],
        },
        {
          id: "kit_nature",
          title: "Kit 4 — nature",
          status: "approved",
          description: "Round tree, dense grove tree, eucalyptus, bush, flower bed, rock, bamboo, reeds, grass tuft.",
          spec: "ART-ENVIRONMENT",
          brief: "props/kit_nature/brief.md",
          notes: "Riddle clues (bamboo, eucalyptus, reeds) recognisable at small size. Generated with gemini-3-pro-image (2K, 16:9).",
          images: [
            { file: "props/kit_nature/sheet_v1.jpg", label: "sheet_v1 (chosen)", required: true },
            { file: "props/kit_nature/sheet_v2.jpg", label: "sheet_v2 (alternative)" },
            { file: "props/kit_nature/model_preview.png", label: "3D model preview" },
          ],
        },
        {
          id: "kit_water",
          title: "Kit 5 — water",
          status: "approved",
          description: "Flowing river (straight, curve), still pond (tile, edge), wooden bridge, jetty, lily pads, duck, frog.",
          spec: "ART-ENVIRONMENT",
          brief: "props/kit_water/brief.md",
          notes: "River clearly flowing vs. pond clearly still (zebra vs. hippo riddle). Generated with gemini-3-pro-image (2K, 16:9).",
          images: [
            { file: "props/kit_water/sheet_v1.jpg", label: "sheet_v1 (chosen)", required: true },
            { file: "props/kit_water/sheet_v2.jpg", label: "sheet_v2 (alternative)" },
            { file: "props/kit_water/model_preview.png", label: "3D model preview" },
          ],
        },
        {
          id: "kit_barriers",
          title: "Kit 6 — barriers",
          status: "approved",
          description: "Road block, repair sign (shovel pictogram), zookeeper cart, traffic cone, fallen tree, closed zoo gate.",
          spec: "ART-ENVIRONMENT",
          brief: "props/kit_barriers/brief.md",
          notes: "Friendly \"not yet\" barriers that seal locked areas. Generated with gemini-3-pro-image (2K, 16:9).",
          images: [
            { file: "props/kit_barriers/sheet_v1.jpg", label: "sheet_v1 (chosen)", required: true },
            { file: "props/kit_barriers/sheet_v2.jpg", label: "sheet_v2 (alternative)" },
            { file: "props/kit_barriers/model_preview.png", label: "3D model preview" },
          ],
        },
        {
          id: "kit_buildings",
          title: "Buildings \u2014 entrance arch, zookeeper house",
          status: "in-review",
          description: "entrance_arch (stone pillars, wooden arch with blank sign, turnstiles, ticket booth) and zookeeper_house (closed + cutaway with the roof removed).",
          spec: "ART-ENVIRONMENT",
          brief: "props/kit_buildings/brief.md",
          notes: "Chosen sheet_v2 (cutaway roof fully removed; arch beam a bit lopsided); v1 alternative (nicer arch, cutaway keeps half the roof). zookeeper_house is not placed in level-1.toml yet.",
          images: [
            { file: "props/kit_buildings/sheet_v2.jpg", label: "sheet_v2 (chosen)", required: true },
            { file: "props/kit_buildings/sheet_v1.jpg", label: "sheet_v1 (alternative)" },
          ],
        },
        {
          id: "food_storage_building",
          title: "Food storage barn (closed + cutaway)",
          status: "in-review",
          description: "Red wooden barn, open double door, blank sign; cutaway with the roof removed showing shelves and ~10 food crates with blank labels (user decision: removable roof, GAME-PLAYER \u00a72).",
          spec: "ART-ENVIRONMENT",
          brief: "props/food_storage_building/brief.md",
          notes: "Chosen sheet_v2; v1 alternative (only 7 crates). Door is in the gable end \u2014 works if the ridge runs north\u2013south over the 8 m south facade.",
          images: [
            { file: "props/food_storage_building/sheet_v2.jpg", label: "sheet_v2 (chosen)", required: true },
            { file: "props/food_storage_building/sheet_v1.jpg", label: "sheet_v1 (alternative)" },
          ],
        },
        {
          id: "kit_enclosure_buildings",
          title: "Enclosure buildings \u2014 zebra, hippo, panda",
          status: "in-review",
          description: "stone_arch_shelter (open both ends), hut_wood (closed + cutaway), pool_tiled; panda_shelter, panda_platform, bamboo_feeding_rack (wood only).",
          spec: "ART-ENVIRONMENT",
          brief: "props/kit_enclosure_buildings/brief.md",
          notes: "Zebra/hippo: chosen sheet_zebra_hippo_v3 (edit of v1: duplicate hut and cutaway roof removed); v1 alternative. Panda: chosen sheet_panda_v2; v1 alternative.",
          images: [
            { file: "props/kit_enclosure_buildings/sheet_zebra_hippo_v3.jpg", label: "zebra + hippo (chosen v3)", required: true },
            { file: "props/kit_enclosure_buildings/sheet_panda_v2.jpg", label: "panda (chosen v2)", required: true },
            { file: "props/kit_enclosure_buildings/sheet_zebra_hippo_v1.jpg", label: "zebra + hippo v1 (alternative)" },
            { file: "props/kit_enclosure_buildings/sheet_panda_v1.jpg", label: "panda v1 (alternative)" },
          ],
        },
        {
          id: "rock_hill_cave",
          title: "Rock hill with cave (closed + cutaway)",
          status: "in-review",
          description: "Grey boulder hill with bushes and a dark cool cave mouth; cutaway with the rock roof removed (3 \u00d7 3 m stone floor, puddle).",
          spec: "ART-ENVIRONMENT",
          brief: "props/rock_hill_cave/brief.md",
          notes: "Chosen sheet_v3 (edit of v1 without wooden mine posts); v1 alternative.",
          images: [
            { file: "props/rock_hill_cave/sheet_v3.jpg", label: "sheet_v3 (chosen)", required: true },
            { file: "props/rock_hill_cave/sheet_v1.jpg", label: "sheet_v1 (alternative)" },
          ],
        },
        {
          id: "kit_furniture",
          title: "Bench and feeding trough",
          status: "in-review",
          description: "bench (2 m, backrest) and feeding_trough for care feeding (GAME-FAMILY \u00a74) \u2014 empty and filled with hay; clearly not a water trough.",
          spec: "ART-ENVIRONMENT",
          brief: "props/kit_furniture/brief.md",
          notes: "Chosen sheet_v1; v2 alternative.",
          images: [
            { file: "props/kit_furniture/sheet_v1.jpg", label: "sheet_v1 (chosen)", required: true },
            { file: "props/kit_furniture/sheet_v2.jpg", label: "sheet_v2 (alternative)" },
          ],
        },
      ],
    },
  ],
};
