#!/usr/bin/env python3
"""Regenerate specs/INDEX.md from spec frontmatter. Usage: python3 tools/spec_index.py [--check]"""
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPECS = ROOT / "specs"
ASPECTS = [("product", "Product"), ("gameplay", "Gameplay"), ("content", "Content"), ("art", "Art"), ("tech", "Tech"),
           ("performance", "Performance")]
STATUSES = ["draft", "review", "approved", "implemented", "deprecated"]
SKIP = {"README.md", "INDEX.md", "glossary.md", "open-questions.md"}


def frontmatter(text):
    m = re.match(r"---\n(.*?)\n---\n", text, re.S)
    if not m:
        return None
    fm = {}
    for line in m.group(1).splitlines():
        k, _, v = line.partition(":")
        v = v.split("  #")[0].strip()
        if v.startswith("["):
            v = [x.strip() for x in v.strip("[]").split(",") if x.strip()]
        fm[k.strip()] = v
    return fm


def question_status():
    st = {}
    for line in (SPECS / "open-questions.md").read_text().splitlines():
        m = re.match(r"\|\s*(Q-\d+)\s*\|.*?\|\s*[^|]*?\s*\|\s*(?:yes|no)[^|]*\|\s*(open|answered|partly answered|proposed|superseded)\b", line)
        if m:
            st[m.group(1)] = m.group(2)
    return st


def main():
    qs = question_status()
    rows = {a: [] for a, _ in ASPECTS}
    problems = []
    for p in sorted(SPECS.rglob("*.md")):
        rel = p.relative_to(SPECS)
        if p.name in SKIP or rel.parts[0] == "fixes" or p.name.startswith("_legacy-"):
            continue
        text = p.read_text()
        fm = frontmatter(text)
        if not fm:
            problems.append(f"no frontmatter: {rel}")
            continue
        body = text.split("\n---\n", 1)[1]
        prefix = fm.get("test_prefix", "")
        tests = sum(1 for l in body.splitlines()
                    if re.match(rf"\|\s*{re.escape(prefix)}-[\w-]*\d+\s*\|", l) and "Retired" not in l) if prefix else 0
        openq = sorted({q for q in re.findall(r"Q-\d+", body) if qs.get(q, "open") != "answered"})
        fm.update(tests=tests, openq=openq, rel=str(rel))
        if fm.get("aspect") not in rows:
            problems.append(f"bad aspect: {rel}")
            continue
        rows[fm["aspect"]].append(fm)
    out = ["# Spec index", "",
           "> **Generated by `tools/spec_index.py` (spec-manager agent) from spec frontmatter — do not edit by hand.**",
           "> Tests = number of active test case rows (retired rows not counted); Open Q = `Q-###` referenced in the spec that are not `answered`.",
           "> Not listed: `README.md`, `glossary.md` (PROD-GLOSSARY), `open-questions.md`, `fixes/`.", ""]
    counts = {s: 0 for s in STATUSES}
    total = tests_total = 0
    ids = set()
    for a, title in ASPECTS:
        if not rows[a]:
            continue
        out += [f"## {title}", "", "| ID | Title | Status | Depends on | Tests | Open Q | File |", "|---|---|---|---|---|---|---|"]
        for fm in sorted(rows[a], key=lambda f: f["id"]):
            if fm["id"] in ids:
                problems.append(f"duplicate id {fm['id']}")
            ids.add(fm["id"])
            counts[fm["status"]] = counts.get(fm["status"], 0) + 1
            total += 1
            tests_total += fm["tests"]
            dep = ", ".join(fm.get("depends_on") or []) or "—"
            oq = ", ".join(fm["openq"]) or "—"
            out.append(f"| {fm['id']} | {fm['title']} | {fm['status']} | {dep} | {fm['tests']} | {oq} | [{fm['rel']}]({fm['rel']}) |")
        out.append("")
    for a in rows:
        for fm in rows[a]:
            for d in fm.get("depends_on") or []:
                if d not in ids:
                    problems.append(f"{fm['id']}: unknown depends_on {d}")
            if not fm["rel"].startswith({"product": "00", "gameplay": "10", "content": "20", "art": "30", "tech": "40",
                                         "performance": "50"}[a]):
                problems.append(f"{fm['id']}: folder does not match aspect")
    qc = {}
    for s in qs.values():
        qc[s] = qc.get(s, 0) + 1
    out.append(f"**Summary:** {total} specs — " + ", ".join(f"{s}: {counts[s]}" for s in STATUSES)
               + f"; {tests_total} test cases; questions: " + ", ".join(f"{k}: {v}" for k, v in sorted(qc.items())) + ".")
    new = "\n".join(out) + "\n"
    target = SPECS / "INDEX.md"
    for pr in problems:
        print("PROBLEM:", pr)
    if "--check" in sys.argv:
        sys.exit(0 if target.read_text() == new and not problems else 1)
    target.write_text(new)
    print(f"wrote {target} ({total} specs)")


main()
