"""Writes the audio block of assets/manifest.toml (between the BEGIN/END markers) from the
cue tables of the synth scripts plus the generated animal-call candidates (ART-SOUND).
Every entry is approved = false; only a human sets approved = true after listening.
Run: python3 tools/sound/register.py"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
MANIFEST = os.path.join(REPO, "assets", "manifest.toml")
BEGIN = "# BEGIN audio (generated by tools/sound/register.py - do not edit by hand)"
END = "# END audio"

import doors, pickups, steps, ui  # noqa: E402

GEMINI = "gemini-3.1-flash-tts-preview"
# Candidates from the Gemini feasibility test (art/sound/brief.md, calls 2 and 3).
ANIMALS = {
    "animal_zebra_call": ("animals", 1, GEMINI,
                          "Make a short, cute cartoon horse whinny sound, like a happy zebra: a rising, "
                          "wobbling, playful 'nyeeeh-hehehe'. Only the animal sound, no words."),
    "animal_koala_call": ("animals", 1, GEMINI,
                          "Make a tiny, cute koala sound: a soft squeaky grunt, 'hnk-eek!', playful and "
                          "friendly. Only the animal sound, no words."),
}


def q(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def entry(cue, group, variants, extra):
    lines = ["[[asset]]", f"id = {q(cue)}", 'kind = "audio"', 'spec = "ART-SOUND"',
             "concept_approved = false", f"group = {q(group)}", f"variants = {variants}",
             f"files = {q(f'assets/audio/{group}/{cue}_<n>.ogg')}"]
    lines += extra
    lines.append("approved = false")
    return "\n".join(lines)


def main():
    blocks = []
    for mod in (steps, doors, pickups, ui):
        for cue, (group, _fn, variants) in mod.CUES.items():
            blocks.append(entry(cue, group, variants, [
                'licence = "own"', 'source = "synthesised"',
                f'script = {q(f"tools/sound/{mod.__name__}.py")}']))
    for cue, (group, variants, model, prompt) in ANIMALS.items():
        blocks.append(entry(cue, group, variants, [
            'licence = "generated"', 'source = "gemini-tts-candidate"', f"model = {q(model)}",
            f"prompt = {q(prompt)}"]))
    text = open(MANIFEST, encoding="utf-8").read()
    text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", "", text, flags=re.S).rstrip() + "\n"
    text += "\n" + BEGIN + "\n\n" + "\n\n".join(blocks) + "\n\n" + END + "\n"
    open(MANIFEST, "w", encoding="utf-8").write(text)
    print(f"{len(blocks)} audio entries written")


if __name__ == "__main__":
    main()
