"""Writes the audio block of assets/manifest.toml (between the BEGIN/END markers) from the
cue tables of the synth scripts and tools/sound/animals.py (real recordings, ART-SOUND).
Every entry is approved = false; only a human sets approved = true after listening.
Run: python3 tools/sound/register.py"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
MANIFEST = os.path.join(REPO, "assets", "manifest.toml")
BEGIN = "# BEGIN audio (generated by tools/sound/register.py - do not edit by hand)"
END = "# END audio"

import animals, doors, pickups, steps, steps_real, ui  # noqa: E402

def q(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def entry(cue, group, variants, extra):
    lines = ["[[asset]]", f"id = {q(cue)}", 'kind = "audio"', 'spec = "ART-SOUND"',
             "concept_approved = false", f"group = {q(group)}", f"variants = {variants}",
             f"files = {q(f'assets/audio/{group}/{cue}_<n>.ogg')}"]
    lines += extra
    lines.append("approved = false")
    return "\n".join(lines)


def main():
    blocks = []
    for mod in (steps, doors, pickups, ui):
        for cue, (group, _fn, variants) in mod.CUES.items():
            blocks.append(entry(cue, group, variants, [
                'licence = "own"', 'source = "synthesised"',
                f'script = {q(f"tools/sound/{mod.__name__}.py")}']))
    for cue, recipes in steps_real.CUES.items():
        srcs = sorted({r["src"] for r in recipes}, key=lambda k: -sum(r["src"] == k for r in recipes))
        if srcs == ["runway"]:
            extra = ['licence = "generated"', 'source = "ai-generated"']
        else:
            extra = ['licence = "CC0"', 'source = "real-recording"']
        origins = []
        for k in srcs:
            _u, lic, author, page = steps_real.SOURCES[k]
            origins.append(f"{page} ({lic}, {author})")
        extra += [f"origin_url = {q('; '.join(origins))}", 'retrieved = "2026-09-30"',
                  'script = "tools/sound/steps_real.py"',
                  'cut = ' + q("; ".join(f"{r['member']} {r['st']:+.1f} st lp {r['lp']} Hz" for r in recipes))]
        if "runway" in srcs:
            extra.append('prompt = ' + q(" | ".join(f"{k}: {v[0]}" for k, v in steps_real.RUNWAY_PROMPTS.items())))
            extra.append('note = "Runway eleven_text_to_sound_v2; commercial use allowed per Runway terms (Q-250)"')
        blocks.append(entry(cue, "steps", len(recipes), extra))
    today = "2026-09-30"  # download date of the sources (sound artist run)
    for cue, rc in animals.CUES.items():
        url, member, lic, author, page = animals.SOURCES[rc["src"]]
        extra = [f'licence = "{lic}"', 'source = "real-recording"', f"origin_url = {q(page)}",
                 f"author = {q(author)}", f"retrieved = {q(today)}", 'script = "tools/sound/animals.py"',
                 f'cut = "{rc["t0"]}-{rc["t1"]} s, pitch {rc.get("st", 0):+d} st, low-pass {rc.get("lp", 8000)} Hz"']
        if cue in animals.STAND_IN:
            extra.append(f"note = {q(animals.STAND_IN[cue])}")
        blocks.append(entry(cue, "animals", 1, extra))
    for cue in animals.GOLDFISH:
        blocks.append(entry(cue, "animals", 1, ['licence = "own"', 'source = "synthesised"',
                                                'script = "tools/sound/animals.py"']))
    text = open(MANIFEST, encoding="utf-8").read()
    text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", "", text, flags=re.S).rstrip() + "\n"
    text += "\n" + BEGIN + "\n\n" + "\n\n".join(blocks) + "\n\n" + END + "\n"
    open(MANIFEST, "w", encoding="utf-8").write(text)
    print(f"{len(blocks)} audio entries written")


if __name__ == "__main__":
    main()
